//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DBAccessor {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DSBenutzer : DataSet {
        
        private benutzerDataTable tablebenutzer;
        
        public DSBenutzer() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DSBenutzer(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["benutzer"] != null)) {
                    this.Tables.Add(new benutzerDataTable(ds.Tables["benutzer"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public benutzerDataTable benutzer {
            get {
                return this.tablebenutzer;
            }
        }
        
        public override DataSet Clone() {
            DSBenutzer cln = ((DSBenutzer)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["benutzer"] != null)) {
                this.Tables.Add(new benutzerDataTable(ds.Tables["benutzer"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tablebenutzer = ((benutzerDataTable)(this.Tables["benutzer"]));
            if ((this.tablebenutzer != null)) {
                this.tablebenutzer.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "DSBenutzer";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/DSBenutzer.xsd";
            this.Locale = new System.Globalization.CultureInfo("de-DE");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tablebenutzer = new benutzerDataTable();
            this.Tables.Add(this.tablebenutzer);
        }
        
        private bool ShouldSerializebenutzer() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void benutzerRowChangeEventHandler(object sender, benutzerRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class benutzerDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnUserID;
            
            private DataColumn columnName;
            
            private DataColumn columnPasswort;
            
            private DataColumn columnGruppenID;
            
            internal benutzerDataTable() : 
                    base("benutzer") {
                this.InitClass();
            }
            
            internal benutzerDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn UserIDColumn {
                get {
                    return this.columnUserID;
                }
            }
            
            internal DataColumn NameColumn {
                get {
                    return this.columnName;
                }
            }
            
            internal DataColumn PasswortColumn {
                get {
                    return this.columnPasswort;
                }
            }
            
            internal DataColumn GruppenIDColumn {
                get {
                    return this.columnGruppenID;
                }
            }
            
            public benutzerRow this[int index] {
                get {
                    return ((benutzerRow)(this.Rows[index]));
                }
            }
            
            public event benutzerRowChangeEventHandler benutzerRowChanged;
            
            public event benutzerRowChangeEventHandler benutzerRowChanging;
            
            public event benutzerRowChangeEventHandler benutzerRowDeleted;
            
            public event benutzerRowChangeEventHandler benutzerRowDeleting;
            
            public void AddbenutzerRow(benutzerRow row) {
                this.Rows.Add(row);
            }
            
            public benutzerRow AddbenutzerRow(string Name, string Passwort, int GruppenID) {
                benutzerRow rowbenutzerRow = ((benutzerRow)(this.NewRow()));
                rowbenutzerRow.ItemArray = new object[] {
                        null,
                        Name,
                        Passwort,
                        GruppenID};
                this.Rows.Add(rowbenutzerRow);
                return rowbenutzerRow;
            }
            
            public benutzerRow FindByUserID(int UserID) {
                return ((benutzerRow)(this.Rows.Find(new object[] {
                            UserID})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                benutzerDataTable cln = ((benutzerDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new benutzerDataTable();
            }
            
            internal void InitVars() {
                this.columnUserID = this.Columns["UserID"];
                this.columnName = this.Columns["Name"];
                this.columnPasswort = this.Columns["Passwort"];
                this.columnGruppenID = this.Columns["GruppenID"];
            }
            
            private void InitClass() {
                this.columnUserID = new DataColumn("UserID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUserID);
                this.columnName = new DataColumn("Name", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnName);
                this.columnPasswort = new DataColumn("Passwort", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPasswort);
                this.columnGruppenID = new DataColumn("GruppenID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnGruppenID);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnUserID}, true));
                this.columnUserID.AutoIncrement = true;
                this.columnUserID.AllowDBNull = false;
                this.columnUserID.ReadOnly = true;
                this.columnUserID.Unique = true;
                this.columnName.AllowDBNull = false;
                this.columnPasswort.AllowDBNull = false;
                this.columnGruppenID.AllowDBNull = false;
            }
            
            public benutzerRow NewbenutzerRow() {
                return ((benutzerRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new benutzerRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(benutzerRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.benutzerRowChanged != null)) {
                    this.benutzerRowChanged(this, new benutzerRowChangeEvent(((benutzerRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.benutzerRowChanging != null)) {
                    this.benutzerRowChanging(this, new benutzerRowChangeEvent(((benutzerRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.benutzerRowDeleted != null)) {
                    this.benutzerRowDeleted(this, new benutzerRowChangeEvent(((benutzerRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.benutzerRowDeleting != null)) {
                    this.benutzerRowDeleting(this, new benutzerRowChangeEvent(((benutzerRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovebenutzerRow(benutzerRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class benutzerRow : DataRow {
            
            private benutzerDataTable tablebenutzer;
            
            internal benutzerRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tablebenutzer = ((benutzerDataTable)(this.Table));
            }
            
            public int UserID {
                get {
                    return ((int)(this[this.tablebenutzer.UserIDColumn]));
                }
                set {
                    this[this.tablebenutzer.UserIDColumn] = value;
                }
            }
            
            public string Name {
                get {
                    return ((string)(this[this.tablebenutzer.NameColumn]));
                }
                set {
                    this[this.tablebenutzer.NameColumn] = value;
                }
            }
            
            public string Passwort {
                get {
                    return ((string)(this[this.tablebenutzer.PasswortColumn]));
                }
                set {
                    this[this.tablebenutzer.PasswortColumn] = value;
                }
            }
            
            public int GruppenID {
                get {
                    return ((int)(this[this.tablebenutzer.GruppenIDColumn]));
                }
                set {
                    this[this.tablebenutzer.GruppenIDColumn] = value;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class benutzerRowChangeEvent : EventArgs {
            
            private benutzerRow eventRow;
            
            private DataRowAction eventAction;
            
            public benutzerRowChangeEvent(benutzerRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public benutzerRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
