//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DBAccessor {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DSUserantworttext : DataSet {
        
        private userantworttextDataTable tableuserantworttext;
        
        public DSUserantworttext() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DSUserantworttext(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["userantworttext"] != null)) {
                    this.Tables.Add(new userantworttextDataTable(ds.Tables["userantworttext"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public userantworttextDataTable userantworttext {
            get {
                return this.tableuserantworttext;
            }
        }
        
        public override DataSet Clone() {
            DSUserantworttext cln = ((DSUserantworttext)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["userantworttext"] != null)) {
                this.Tables.Add(new userantworttextDataTable(ds.Tables["userantworttext"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableuserantworttext = ((userantworttextDataTable)(this.Tables["userantworttext"]));
            if ((this.tableuserantworttext != null)) {
                this.tableuserantworttext.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "DSUserantworttext";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/DSUserantworttext.xsd";
            this.Locale = new System.Globalization.CultureInfo("de-DE");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableuserantworttext = new userantworttextDataTable();
            this.Tables.Add(this.tableuserantworttext);
        }
        
        private bool ShouldSerializeuserantworttext() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void userantworttextRowChangeEventHandler(object sender, userantworttextRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class userantworttextDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnUawtID;
            
            private DataColumn columnr_FrageID;
            
            private DataColumn columnText;
            
            internal userantworttextDataTable() : 
                    base("userantworttext") {
                this.InitClass();
            }
            
            internal userantworttextDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn UawtIDColumn {
                get {
                    return this.columnUawtID;
                }
            }
            
            internal DataColumn r_FrageIDColumn {
                get {
                    return this.columnr_FrageID;
                }
            }
            
            internal DataColumn TextColumn {
                get {
                    return this.columnText;
                }
            }
            
            public userantworttextRow this[int index] {
                get {
                    return ((userantworttextRow)(this.Rows[index]));
                }
            }
            
            public event userantworttextRowChangeEventHandler userantworttextRowChanged;
            
            public event userantworttextRowChangeEventHandler userantworttextRowChanging;
            
            public event userantworttextRowChangeEventHandler userantworttextRowDeleted;
            
            public event userantworttextRowChangeEventHandler userantworttextRowDeleting;
            
            public void AdduserantworttextRow(userantworttextRow row) {
                this.Rows.Add(row);
            }
            
            public userantworttextRow AdduserantworttextRow(int r_FrageID, string Text) {
                userantworttextRow rowuserantworttextRow = ((userantworttextRow)(this.NewRow()));
                rowuserantworttextRow.ItemArray = new object[] {
                        null,
                        r_FrageID,
                        Text};
                this.Rows.Add(rowuserantworttextRow);
                return rowuserantworttextRow;
            }
            
            public userantworttextRow FindByUawtID(int UawtID) {
                return ((userantworttextRow)(this.Rows.Find(new object[] {
                            UawtID})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                userantworttextDataTable cln = ((userantworttextDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new userantworttextDataTable();
            }
            
            internal void InitVars() {
                this.columnUawtID = this.Columns["UawtID"];
                this.columnr_FrageID = this.Columns["r_FrageID"];
                this.columnText = this.Columns["Text"];
            }
            
            private void InitClass() {
                this.columnUawtID = new DataColumn("UawtID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUawtID);
                this.columnr_FrageID = new DataColumn("r_FrageID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnr_FrageID);
                this.columnText = new DataColumn("Text", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnText);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnUawtID}, true));
                this.columnUawtID.AutoIncrement = true;
                this.columnUawtID.AllowDBNull = false;
                this.columnUawtID.ReadOnly = true;
                this.columnUawtID.Unique = true;
                this.columnr_FrageID.AllowDBNull = false;
            }
            
            public userantworttextRow NewuserantworttextRow() {
                return ((userantworttextRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new userantworttextRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(userantworttextRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.userantworttextRowChanged != null)) {
                    this.userantworttextRowChanged(this, new userantworttextRowChangeEvent(((userantworttextRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.userantworttextRowChanging != null)) {
                    this.userantworttextRowChanging(this, new userantworttextRowChangeEvent(((userantworttextRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.userantworttextRowDeleted != null)) {
                    this.userantworttextRowDeleted(this, new userantworttextRowChangeEvent(((userantworttextRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.userantworttextRowDeleting != null)) {
                    this.userantworttextRowDeleting(this, new userantworttextRowChangeEvent(((userantworttextRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveuserantworttextRow(userantworttextRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class userantworttextRow : DataRow {
            
            private userantworttextDataTable tableuserantworttext;
            
            internal userantworttextRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableuserantworttext = ((userantworttextDataTable)(this.Table));
            }
            
            public int UawtID {
                get {
                    return ((int)(this[this.tableuserantworttext.UawtIDColumn]));
                }
                set {
                    this[this.tableuserantworttext.UawtIDColumn] = value;
                }
            }
            
            public int r_FrageID {
                get {
                    return ((int)(this[this.tableuserantworttext.r_FrageIDColumn]));
                }
                set {
                    this[this.tableuserantworttext.r_FrageIDColumn] = value;
                }
            }
            
            public string Text {
                get {
                    try {
                        return ((string)(this[this.tableuserantworttext.TextColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Der Wert kann nicht ermittelt werden, da er DBNull ist.", e);
                    }
                }
                set {
                    this[this.tableuserantworttext.TextColumn] = value;
                }
            }
            
            public bool IsTextNull() {
                return this.IsNull(this.tableuserantworttext.TextColumn);
            }
            
            public void SetTextNull() {
                this[this.tableuserantworttext.TextColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class userantworttextRowChangeEvent : EventArgs {
            
            private userantworttextRow eventRow;
            
            private DataRowAction eventAction;
            
            public userantworttextRowChangeEvent(userantworttextRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public userantworttextRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
